"""Make age column non-nullable

Revision ID: 494fbd12f183
Revises: 823cc79b2465
Create Date: 2025-09-19 12:49:26.517073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494fbd12f183'
down_revision: Union[str, Sequence[str], None] = '823cc79b2465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
